name: Deploy to vps
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - uses: actions/checkout@master

      - name: Copiar archivos a la vps 
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: ${{ secrets.HOST }}
          remote: ${{ secrets.REMOTE }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
