name: Deploy to vps
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - uses: actions/checkout@v2
      - uses: a-was/scp-action@v1
        with:
          host: ${{ env.REMOTE_HOST }}
          user: ${{ env.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination: /home/gonzalo/